### ISSUE TITLE
Prepare Docker images for geth and prometheus

### ISSUE THREAD

**Issue by veaceslavdoina** [codex-storage/cs-codex-dist-tests#34]
For Distributed Tests we are using now 4 components
 - [nim-codex](https://github.com/codex-storage/nim-codex)
 - [codex-contracts-eth](https://github.com/codex-storage/codex-contracts-eth)
 - geth
 - prometheus

For the first two we [already prepared automated Docker builds for AMD/ARM64](https://github.com/codex-storage/nim-codex/issues/412) and it is required to build images in a similar way for last two components.

We may use existing Ben's code as a reference
 - [benbierens/geth-for-codex](https://github.com/benbierens/geth-for-codex)
 - [benbierens/prometheus-envconf](https://github.com/benbierens/prometheus-envconf)

FYI: @benbierens and @emizzle

**Comment by veaceslavdoina** [comment]
We also prepared an updated image for [codex-contracts-eth](https://github.com/codex-storage/codex-contracts-eth), which works in a slightly different way and we store it in a separate DockerHub repository
 - [codexstorage/dist-tests-codex-contracts-eth](https://hub.docker.com/r/codexstorage/dist-tests-codex-contracts-eth/tags)

**Test Docker image**
```shell
docker run --rm codexstorage/dist-tests-codex-contracts-eth:sha-b4e4897
```

**Comment by veaceslavdoina** [comment]
@benbierens, we recently switched to the [new tagging approach for Docker images](42)
```shell
# nim-codex
docker run --rm codexstorage/nim-codex:latest-dist-tests

# codex-contracts-eth
docker run --rm codexstorage/codex-contracts-eth:latest-dist-tests

# dist-tests-geth
docker run --rm codexstorage/dist-tests-geth:latest

# dist-tests-prometheus
docker run --rm codexstorage/dist-tests-prometheus:latest
```
1. Can you please try to move to the new images.
2. You've recently introduced support for images with a `latest` tag for nim-codex, but we will have `latest-dist-tests`. Will your approach work with that tag as well?

**Comment by benbierens** [comment]
This all checks out. The new images work. Useful version information makes it to the logs, (not just 'latest') and the master branch for the dist-test repo has been updated to use the new images.
Thanks very much! :D

**Comment by veaceslavdoina** [comment]
Thank you for the confirmation. Repository [`dist-tests-codex-contracts-eth`](https://hub.docker.com/repository/docker/codexstorage/dist-tests-codex-contracts-eth) was deleted as we have images in the base repository([`codex-contracts-eth`](https://hub.docker.com/repository/docker/codexstorage/codex-contracts-eth)) with a separate tag.
