### ISSUE TITLE
Make Docker workflows more adjustable

### ISSUE THREAD

**Issue by veaceslavdoina** [codex-storage/cs-codex-dist-tests#42]
### Intro
The idea is coming from @emizzle and basically it is about to make [existing Docker workflow](../blob/master/.github/workflows/docker.yml) more adjustable by passing build parameters and also use `latest` tag for every build
- Create a [reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows) based on an existing one
- Create `latest` tag for all builds and distinguish them by name
   ```
   nim-codex:latest            - latest release
   nim-codex:latest-dist-tests - latest build for dist-tests
   nim-codex:latest-custom     - latest build for custom
   ```
- Always use same DockerHub repository and distinguish images by tags, like
  ```
  nim-codex:latest
  nim-codex:latest-dist-tests
  ```

And we also should take care about how to identify which GitHub commit was used for the latest tag. One of the way to do that is to push tags with short sha as well, like we are doing it right now.

But in case when we would like to identify `latest` tag over the time it might be required to perform a check based on the image usage and push time.

### Progress
- [x] codex-storage/nim-codex/pull/518
- [x] codex-storage/codex-contracts-eth/pull/67)
- [x] codex-storage/dist-tests-geth/pull/1
- [x] codex-storage/dist-tests-prometheus/pull/1
- [x] #45

**Comment by benbierens** [comment]
You can currently change the codex image being used by setting the `CODEXDOCKERIMAGE` variable. If you want to use 'latest', set it to `codexstorage/nim-codex:latest`.
I will now check to make sure that when a latest image is used, the logs created will contain the info required to be able to identify the specific Codex version being used.

**Comment by emizzle** [comment]
Any progress on this? It would be really convenient if `:lastest` referenced latest master of the respective repository.

**Comment by veaceslavdoina** [comment]
> Any progress on this? It would be really convenient if `:lastest` referenced latest master of the respective repository.

Not, yet. Sorry for such a delay. Will change my priorities, but need to finish some stuff around.

**Comment by veaceslavdoina** [comment]
There is another way to optimize workflows using [Creating a composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action). But accordingly to the [How to start using reusable workflows with GitHub Actions](https://github.blog/2022-02-10-using-reusable-workflows-github-actions/), they are limited for usage with Secrets, Platforms, Conditions and in our case we need to push images using secrets and create builds for amd64/arm64.
We are using composite action in [nim-codex/actions/nimbus-build-system](https://github.com/codex-storage/nim-codex/blob/master/.github/actions/nimbus-build-system).

Information about composite action limitations maybe not up to date, but we are continuing with [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows).

**Comment by veaceslavdoina** [comment]
This is exactly our case - [Multi-platform image with GitHub Actions/Distribute build across multiple runners](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners), but for some reason it doesn't work as expected.

Need to check why push by digest works but image creation doesn't.

**Comment by veaceslavdoina** [comment]
Looks there was an issue with DockerHub and I didn't show anything in the Tags section.

Test today in the morning was successful and we can see images pushed yesterday as well.

<details>
<summary>Screenshots</summary>

<img width="1260" alt="Screenshot 2023-08-14 at 08 17 35" src="https://github.com/codex-storage/cs-codex-dist-tests/assets/20563034/4830e9d9-c4f9-43eb-b389-5636e874b5a9">
<img width="1249" alt="Screenshot 2023-08-14 at 08 17 24" src="https://github.com/codex-storage/cs-codex-dist-tests/assets/20563034/5744851f-88e9-4b75-8b42-8504b139cc30">


</details>

So, we can adopt workflow to be reusable.

**Comment by emizzle** [comment]
Thanks a lot, Slavas! I should be able to get around to testing this tomorrow 👍

**Comment by emizzle** [comment]
I see, this was a test workflow to be applied to the images, got it. I'll test once the `:latest` images are up.

**Comment by veaceslavdoina** [comment]
Eric, I'm working that now to make it reusable and to handle cases like
```yaml
IMAGE_LATEST: true
IMAGE_SHA: false
IMAGE_SUFFIX: custom
IMAGE_SUFFIX_ONLATEST: false
```

Should be done today.

**Comment by veaceslavdoina** [comment]
First [PR](/codex-storage/nim-codex/pull/518) is ready and it is about nim-codex.

It probably make sense to set `tag_sha=true` when we set `tag_latest=true` and in that way we will have `latest` tag and specific `sha-123456` build as well.

| # | Configuration                                                         | Git Commit                            | Git Tag                             |
| - | --------------------------------------------------------------------- | ------------------------------------- | ----------------------------------- |
| 1 | `IMAGE_LATEST=false` <br> `IMAGE_SHA=true`                            | `sha-af3cc6d`                         | `0.0.1`                             |
| 2 | `IMAGE_LATEST=true` <br> `IMAGE_SHA=false`                            | `latest`                              | `0.0.1` <br> `latest`               |
| 3 | `IMAGE_LATEST=true` <br> `IMAGE_SHA=true`                             | `latest`, `sha-af3cc6d`               | `latest` <br> `0.0.1`               |
| 4 | `IMAGE_LATEST=false` <br> `IMAGE_SHA=true` <br> `IMAGE_SUFFIX=custom` | `sha-af3cc6d-custom`                  | `0.0.1-custom`                      |
| 5 | `IMAGE_LATEST=true` <br> `IMAGE_SHA=false` <br> `IMAGE_SUFFIX=custom` | `latest-custom`                       | `latest-custom` <br> `0.0.1-custom` |
| 6 | `IMAGE_LATEST=true` <br> `IMAGE_SHA=true` <br> `IMAGE_SUFFIX=custom`  | `latest-custom`, `sha-af3cc6d-custom` | `latest-custom`, `0.0.1-custom`     |

**Comment by veaceslavdoina** [comment]
And some notes about latest tag usage

#### Docker
We should use `--pull=always` parameter to get the newer `latest` image at run
```shell
docker run --rm --pull=always codexstorage/test:latest codex --version
```

#### Kubernetes
We should set `imagePullPolicy: Always` at Pods creation to get the latest image
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: dist-tests-runner
  namespace: cs-codex-dist-tests
  labels:
    name: cs-codex-dist-tests
spec:
  containers:
  - name: cs-codex-dist-tests
    image: codexstorage/cs-codex-dist-tests:lates
    imagePullPolicy: Always
```
Also, we can just skip that policy and Kubernetes will use `Always` policy
> if you omit the `imagePullPolicy` field, and the tag for the container image is `:latest`, `imagePullPolicy` is automatically set to `Always`;

But in our case with Dist-Tests, we are planning to have `lates-dist-test` tag and not just `latest`. And for that, we should set explicitly `imagePullPolicy=Always`.


#### Reference
1. [Why can't I pull the newest image by using the latest tag?](https://cloud.ibm.com/docs/Registry?topic=Registry-troubleshoot-docker-latest)
2. [Kubernetes - Image pull policy](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy)
3. [Kubernetes - Default image pull policy](https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting)
4. [Why We Should Use ‘latest’ Tag on Container Images](https://medium.com/@michael.vittrup.larsen/why-we-should-use-latest-tag-on-container-images-fc0266877ab5)

**Comment by emizzle** [comment]
Very nice work @veaceslavdoina !! I will review this more closely tomorrow.

**Comment by veaceslavdoina** [comment]
One more question - should we consider to use just a `custom` word as a tag, when `latest` is disabled?
| # | Configuration                                                         | Git Commit                     | Git Tag                  |
| - | --------------------------------------------------------------------- | ------------------------------ | ------------------------ |
| 1 | `IMAGE_LATEST=false` <br> `IMAGE_SHA=true` <br> `IMAGE_SUFFIX=custom` | `sha-af3cc6d-custom`, `custom` | `0.0.1-custom`, `custom` |

I was mostly focused on the `latest` tag, but we probably can extend the current implementation in the future if it will be required.

The question is coming from the comparison of the `latest-custom` vs `custom`.

**Comment by emizzle** [comment]
> It probably make sense to set tag_sha=true when we set tag_latest=true and in that way we will have latest tag and specific sha-123456 build as well.

I definitely agree with this, as it will provide the ability to downgrade in case `latest` is broken.

> One more question - should we consider to use just a `custom` word as a tag, when `latest` is disabled?

As long as the sha + custom label exists, eg `sha-af3cc6d-custom`, then I don't think we also need an image with the `custom` word as the tag, as it would be confusing: a user may ask themselves, "Should I use the `latest-custom` or `custom` image for my application?", where they will not know if both images point to the same commits or not, and the reality is they wouldn't.

My opinion is that we would have a maximum of 4 images produced depending on the config params: 
| # | Tag | Description | Configuration |
|--------|--------|--------|--------|
| 1 | `latest` | image built with the latest commit on master | `IMAGE_LATEST=true` |
| 2 | `sha-af3cc6d` | image built with commit `af3cc6d` | `IMAGE_SHA=true` |
| 3 | `latest-custom` | image built with the latest commit on master and custom build/run parameters | `IMAGE_LATEST=true` and `IMAGE_SUFFIX=custom` |
| 4 | `sha-af3cc6d-custom` | image built with commit `af3cc6d` and custom build/run parameters | `IMAGE_SUFFIX=custom` |

**Comment by veaceslavdoina** [comment]
Looks like I've already did it and replaced `IMAGE_*` with `TAG_*`, so no refactoring is needed.

All PR's were approved and merged and we can consider that as solved for now.
