### ISSUE TITLE
Add _STATUS.log for Continuous-Tests

### ISSUE THREAD

**Issue by veaceslavdoina** [codex-storage/cs-codex-dist-tests#62]
We already using actively [recently implemented _STATUS.log](32) for Dist-Tests and it works well. Now we can see all the runs and tests execution status.

It would be very usefully to implement similar `_STATUS.log` log for Continuous-Tests to be able to check execution status from Kibana and Grafana. It is a step for future automation.
Also, we will collect historical data and would be able to analyze it in case of need.

For now, we should check logs locally inside the runner Pod and it is not so comfortable and in case of automation we may not be able to do it.

Should we consider to finish [Add new fields to the _STATUS.log and add run_STATUS.log #38](38) first?

**Comment by benbierens** [comment]
Should be fixed in https://github.com/codex-storage/cs-codex-dist-tests/commit/453a1a35a21f5076bda946cd25a95b4e9ee2ce2c :D
